extends Node

func load_game():
	var save_file = File.new()
	if not save_file.file_exists("user://savefile.save"):
		return
	save_file.open("user://savefile.save", File.READ)
	Global.health = int(save_file.get_var())
	Global.damage = int(save_file.get_var())
	Global.level2 = bool(save_file.get_float())
	Global.level3 = bool(save_file.get_float())
	Global.level4 = bool(save_file.get_float())
	Global.level5 = bool(save_file.get_float())
	Global.volume = int(save_file.get_var())
	Global.doublejump = bool(save_file.get_float())
	Global.dash = bool(save_file.get_float())
	Global.gun = bool(save_file.get_float())
	Global.weaponselect = int(save_file.get_var())
	Global.pistol = bool(save_file.get_float())
	Global.dbshotgun = bool(save_file.get_float())
	Global.lrshotgun = bool(save_file.get_float())
	Global.rifle = bool(save_file.get_float())
	Global.sniper = bool(save_file.get_float())
	Global.murasama = bool(save_file.get_float())
	Global.shell = int(save_file.get_var())
	Global.ammo = int(save_file.get_var())
	Global.longammo = int(save_file.get_var())
	Global.currentammo = int(save_file.get_var())
	Global.currentmaxammo = int(save_file.get_var())
	Global.pistolammo = int(save_file.get_var())
	Global.dbshotgunammo = int(save_file.get_var())
	Global.lrshotgunammo = int(save_file.get_var())
	Global.rifleammo = int(save_file.get_var())
	Global.sniperammo = int(save_file.get_var())
	Global.money = int(save_file.get_var())
	Global.dashcooldown = int(save_file.get_var())
	Global.shieldhealth = int(save_file.get_var())
	Global.shield = bool(save_file.get_float())
	
	print("Loaded")
	save_file.close()
	get_tree().reload_current_scene()

func save_game():
	var save_file = File.new()
	save_file.open("user://savefile.save", File.WRITE)
	save_file.store_var(int(Global.health))
	save_file.store_var(int(Global.damage))
	save_file.store_float(float(Global.level2))
	save_file.store_float(float(Global.level3))
	save_file.store_float(float(Global.level4))
	save_file.store_float(float(Global.level5))
	save_file.store_var(int(Global.volume))
	save_file.store_float(float(Global.doublejump))
	save_file.store_float(float(Global.dash))
	save_file.store_float(float(Global.gun))
	save_file.store_var(int(Global.weaponselect))
	save_file.store_float(float(Global.pistol))
	save_file.store_float(float(Global.dbshotgun))
	save_file.store_float(float(Global.lrshotgun))
	save_file.store_float(float(Global.rifle))
	save_file.store_float(float(Global.sniper))
	save_file.store_float(float(Global.murasama))
	save_file.store_var(int(Global.shell))
	save_file.store_var(int(Global.ammo))
	save_file.store_var(int(Global.longammo))
	save_file.store_var(int(Global.currentammo))
	save_file.store_var(int(Global.currentmaxammo))
	save_file.store_var(int(Global.pistolammo))
	save_file.store_var(int(Global.dbshotgunammo))
	save_file.store_var(int(Global.lrshotgunammo))
	save_file.store_var(int(Global.rifleammo))
	save_file.store_var(int(Global.sniperammo))
	save_file.store_var(int(Global.money))
	save_file.store_var(int(Global.dashcooldown))
	save_file.store_var(int(Global.shieldhealth))
	save_file.store_float(float(Global.shield))

	print("Saved!")
	save_file.close()
